import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import type {Alarm,AlarmCreateInput,AlarmSchedule,AppSettings,IsoWeekday,Station} from '../types.js';
import {JsonLibraryStore,stationKey} from '../storage/store.js';
import {ProviderManager} from '../providers/provider-manager.js';
import {PlayerController} from '../player/player-controller.js';
import {detectPlaybackBackends} from '../player/backend-install.js';
import {canonicalizeAlarmTime,canonicalizeIsoWeekdays,canonicalizeTimeZone,nextOccurrenceForAlarm} from './schedule.js';
import {createSchedulerService,SchedulerService,shouldRunLaunchdOccurrence} from './scheduler.js';
import {connectActiveAlarms} from './active-session.js';
import {createPowerInhibitor} from './inhibitor.js';
import {acquireOccurrenceLock,defaultRunnerUtilities,runAlarm} from './runner.js';
import {AlarmGuardService,runAlarmGuard} from './guard.js';
import {AlarmPowerGuardStore} from './power-guard-store.js';
import {openAlarmControls} from './terminal-launcher.js';
import {hasLiveTui} from './tui-presence.js';
import {createSystemVolumeController} from './system-volume.js';
import {connectRadioSession} from '../agent/session.js';

type Options={values:Map<string,string|true>;positionals:string[]};
export type AlarmCommandDependencies={store?:JsonLibraryStore;scheduler?:SchedulerService};

export async function runAlarmCommand(args:string[],dependencies:AlarmCommandDependencies={}):Promise<void>{
  const store=dependencies.store??new JsonLibraryStore();const scheduler=dependencies.scheduler??createSchedulerService();const [sub='list',...rest]=args;
  if(sub==='list'){const json=rest.includes('--json');const alarms=store.listAlarms();if(json)console.log(JSON.stringify(alarms,null,2));else if(!alarms.length)console.log('No alarms.');else for(const alarm of alarms)console.log(formatAlarm(alarm));return;}
  if(sub==='show'){const alarm=requireAlarm(store,rest[0]);console.log(JSON.stringify({...alarm,nextOccurrence:nextOccurrenceForAlarm(alarm,new Date())?.toISOString()??null},null,2));return;}
  if(sub==='add'){const parsed=parseOptions(rest);if(parsed.positionals.length)throw new Error('Alarm add does not accept positional arguments.');const station=resolveStation(store,required(parsed,'station'));const input=createInput(parsed,station);if(parsed.values.has('fallback'))input.playback.fallbackStation=resolveStation(store,String(parsed.values.get('fallback')));const alarm=store.addAlarm(input);await syncSaved(scheduler,alarm);if(alarm.reliability.keepAwakeUntilAlarm)await reconcileAlarmGuard(alarm);console.log(`alarm=${alarm.id}`);return;}
  if(sub==='edit'){const parsed=parseOptions(rest);if(parsed.positionals.length!==1)throw new Error('Usage: radiocli alarm edit <id> [options]');const id=parsed.positionals[0];const alarm=requireAlarm(store,id);const updated=store.updateAlarm(alarm.id,updatesFromOptions(parsed,store,alarm));await syncSaved(scheduler,updated);if(updated.reliability.keepAwakeUntilAlarm||parsed.values.has('no-guard'))await reconcileAlarmGuard(updated);console.log(`updated=${updated.id}`);return;}
  if(sub==='enable'||sub==='disable'){const alarm=store.toggleAlarm(requiredPos(rest,0),sub==='enable');await syncSaved(scheduler,alarm);await reconcileAlarmGuard(alarm);console.log(`${sub}d=${alarm.id}`);return;}
  if(sub==='remove'){const id=requiredPos(rest,0);requireAlarm(store,id);await scheduler.remove(id);if(!store.removeAlarm(id))throw new Error(`Alarm not found: ${id}`);console.log(`removed=${id}`);return;}
  if(sub==='sync'){const results=await scheduler.syncAll(store.listAlarms());for(const item of results)console.log(`${item.id}=${item.error?`degraded ${item.error}`:item.occurrence?.toISOString()??'disabled'}`);if(results.some(item=>item.error))process.exitCode=1;return;}
  if(sub==='doctor'){const guards=await new AlarmGuardService(new AlarmPowerGuardStore()).status();const active=await statusesOf(await connectActiveAlarms());const powerCapability=createPowerInhibitor().status();const schedulerStatus=await scheduler.runtimeStatus(store.listAlarms());const report={scheduler:schedulerStatus,power:{...powerCapability,active:guards.active||runnerPowerActive(active,schedulerStatus.entries)},guards,active};if(rest.includes('--json'))console.log(JSON.stringify(report,null,2));else{console.log(`scheduler=${report.scheduler.capabilities.supported?'ready':'unsupported'} ${report.scheduler.capabilities.message}`);console.log(`scheduler_degraded=${report.scheduler.entries.filter(item=>!item.healthy).length}`);console.log(`power_guard=${report.power.supported?'ready':'unsupported'} ${report.power.message}`);console.log(`guards=${guards.guards.length}`);console.log(`active=${active.length}`);}return;}
  if(sub==='status'){const active=await selectedActiveStatuses(rest);const guards=await new AlarmGuardService(new AlarmPowerGuardStore()).status();const powerCapability=createPowerInhibitor().status();const schedulerStatus=await scheduler.runtimeStatus(store.listAlarms());console.log(JSON.stringify({active,scheduler:schedulerStatus,guards,power:{...powerCapability,active:guards.active||runnerPowerActive(active,schedulerStatus.entries)}},null,2));return;}
  if(sub==='dismiss'){const active=await requireActive(rest);await active.dismiss();console.log('dismissed=yes');return;}
  if(sub==='snooze'){const minutes=integer(requiredPos(rest,0),'snooze minutes',1,1440);const active=await requireActive(rest.slice(1));await active.snooze(minutes);console.log(`snoozed=${minutes}`);return;}
  if(sub==='keep-playing'){const active=await requireActive(rest);await active.keepPlaying();console.log('keep_playing=yes');return;}
  if(sub==='guard'){const action=rest[0]??'status';const guards=new AlarmGuardService(new AlarmPowerGuardStore());if(action==='start'){const alarm=requireAlarm(store,rest[1]);const result=await guards.start(alarm);console.log(`guard=${result.occurrenceAt}`);}else if(action==='stop')console.log(`stopped=${await guards.stop(rest[1])?'yes':'no'}`);else if(action==='status')console.log(JSON.stringify(await guards.status(),null,2));else throw new Error('Usage: radiocli alarm guard start <id>|stop [id]|status');return;}
  if(sub==='test'){const alarm=requireAlarm(store,rest[0]);await testAlarm(alarm,store);console.log('test=complete');return;}
  if(sub==='internal-run'){const id=requiredPos(rest,0);const at=requiredPos(rest,1);await runAlarm(id,at,createRuntimeDeps(store,scheduler,id));return;}
  if(sub==='internal-launchd'){const id=requiredPos(rest,0);const at=requiredPos(rest,1);if(!shouldRunLaunchdOccurrence(at,new Date()))return;await runAlarm(id,at,createRuntimeDeps(store,scheduler,id));return;}
  if(sub==='internal-guard-run'){await runAlarmGuard(requiredPos(rest,0),requiredPos(rest,1),createPowerInhibitor(),new AlarmPowerGuardStore(),()=>new Date(),defaultRunnerUtilities.wait,rest[2],rest[3]);return;}
  throw new Error(alarmUsage());
}

function createRuntimeDeps(store:JsonLibraryStore,scheduler:SchedulerService,alarmId:string){const providers=new ProviderManager();const alarm=store.getAlarm(alarmId);const detected=detectPlaybackBackends();const settings=alarm?alarmRuntimeSettings(store.snapshot().settings,alarm,detected):{...store.snapshot().settings,preferredBackend:'auto' as const,preferredAirPlayDevice:undefined};const player=new PlayerController(()=>settings);player.refreshDetectedBackends();const cliPath=join(dirname(fileURLToPath(import.meta.url)),'..','cli.js');return{now:()=>new Date(),store,providers,player,scheduler,inhibitor:createPowerInhibitor(),systemVolume:createSystemVolumeController(),preemptInteractivePlayback:async()=>{const client=await connectRadioSession();if(!client)return;const result=await client.call({type:'alarm-preempt'});if(!result.ok)throw new Error(result.message);},acquireLock:acquireOccurrenceLock,createSession:defaultRunnerUtilities.createSession,openControls:()=>openAlarmControls({nodePath:process.execPath,cliPath,hasLiveTui}),wait:defaultRunnerUtilities.wait,subscribeSignals:defaultRunnerUtilities.subscribeSignals,health:scheduler.health};}
export function alarmRuntimeSettings(settings:AppSettings,alarm:Alarm,backends:readonly string[]):AppSettings{const mpvFade=alarm.playback.fadeSeconds>0&&backends.includes('mpv');return{...settings,volume:mpvFade?0:alarm.playback.volume,preferredBackend:mpvFade?'mpv':'auto',preferredAirPlayDevice:undefined};}
async function testAlarm(alarm:Alarm,store:JsonLibraryStore){
  const scheduledAt=new Date(Math.floor(Date.now()/60_000)*60_000);const deadline=Date.now()+10_000;
  const preview={...alarm,id:`test-${process.pid}`,enabled:true,schedule:{type:'once' as const,at:scheduledAt.toISOString()},playback:{...alarm.playback,fadeSeconds:Math.min(alarm.playback.fadeSeconds,8),stopAfterMinutes:1},reliability:{...alarm.reliability,missedRunGraceMinutes:Math.max(1,alarm.reliability.missedRunGraceMinutes)}};
  const settings={...alarmRuntimeSettings(store.snapshot().settings,preview,detectPlaybackBackends()),tuneTimeoutSeconds:3};const player=new PlayerController(()=>settings);player.refreshDetectedBackends();const providers=new ProviderManager();
  const boundedProviders={resolve:(station:Station)=>Promise.race([providers.resolve(station),rejectAt(deadline-3000,'Alarm preview station resolution timed out.')])};
  let interrupt=()=>{};const noOp=()=>({});const runner=runAlarm(preview.id,scheduledAt.toISOString(),{now:()=>new Date(),store:{getAlarm:()=>preview,recordAlarmOutcome:noOp,toggleAlarm:noOp,snoozeAlarm:noOp,addRecent:noOp,startListeningSession:noOp,checkpointActiveListeningSession:noOp,finishActiveListeningSession:noOp},providers:boundedProviders,player,scheduler:{sync:async()=>null},inhibitor:createPowerInhibitor(),acquireLock:()=>()=>{},createSession:defaultRunnerUtilities.createSession,wait:milliseconds=>defaultRunnerUtilities.wait(Math.min(milliseconds,Math.max(0,deadline-Date.now()))),subscribeSignals:handler=>{interrupt=handler;const unsubscribe=defaultRunnerUtilities.subscribeSignals(handler);return()=>{interrupt=()=>{};unsubscribe();};}});
  const result=await enforcePreviewDeadline(runner,()=>interrupt(),()=>player.stop(),Math.max(0,deadline-Date.now()));
  validatePreviewResult(result);
}
export function validatePreviewResult(result:{status?:string;message?:string}){if(result.status!=='played'&&result.status!=='dismissed')throw new Error(result.message??`Alarm preview did not play (${result.status??'unknown'}).`);}
export function rejectAt(deadline:number,message:string):Promise<never>{return new Promise((_,reject)=>{const timer=setTimeout(()=>reject(new Error(message)),Math.max(0,deadline-Date.now()));timer.unref();});}
export async function enforcePreviewDeadline<T>(runner:Promise<T>,interrupt:()=>void,stop:()=>Promise<unknown>,timeoutMs=10_000,cleanupMs=1_500):Promise<T>{let timer:NodeJS.Timeout|undefined;const timeout=new Promise<{timeout:true}>(resolve=>{timer=setTimeout(()=>resolve({timeout:true}),timeoutMs);});let result:{value:T}|{timeout:true};try{result=await Promise.race([runner.then(value=>({value})),timeout]);}finally{if(timer)clearTimeout(timer);}if('value'in result)return result.value;interrupt();const cleanupDeadline=Date.now()+cleanupMs;await settleWithin(Promise.resolve().then(stop).catch(()=>undefined),cleanupDeadline);await settleWithin(runner.then(()=>undefined,()=>undefined),cleanupDeadline);throw new Error(`Alarm preview exceeded its ${Math.round(timeoutMs/1000)}-second playback safety limit; cleanup was given ${cleanupMs}ms.`);}
async function settleWithin(promise:Promise<unknown>,deadline:number):Promise<void>{const remaining=Math.max(0,deadline-Date.now());if(remaining===0)return;let timer:NodeJS.Timeout|undefined;try{await Promise.race([promise,new Promise<void>(resolve=>{timer=setTimeout(resolve,remaining);})]);}finally{if(timer)clearTimeout(timer);}}

function createInput(options:Options,station:Station):AlarmCreateInput{return{label:String(options.values.get('label')||station.name),enabled:!options.values.has('disabled'),station,schedule:scheduleFrom(options),playback:{volume:integer(String(options.values.get('volume')??'40'),'volume',0,100),fadeSeconds:durationSeconds(String(options.values.get('fade')??'0')),stopAfterMinutes:durationMinutes(String(options.values.get('stop-after')??'60')),fallbackStation:options.values.has('fallback')?undefined:undefined},reliability:{missedRunGraceMinutes:integer(String(options.values.get('grace')??'10'),'grace',0,10080),wakeIfSupported:options.values.has('wake'),keepAwakeUntilAlarm:options.values.has('guard')}};}
function updatesFromOptions(options:Options,store:JsonLibraryStore,alarm:Alarm):Partial<Pick<Alarm,'label'|'enabled'|'station'|'schedule'|'playback'|'reliability'>>{const station=options.values.has('station')?resolveStation(store,String(options.values.get('station'))):alarm.station;const playback={...alarm.playback};if(options.values.has('volume'))playback.volume=integer(String(options.values.get('volume')),'volume',0,100);if(options.values.has('fade'))playback.fadeSeconds=durationSeconds(String(options.values.get('fade')));if(options.values.has('stop-after'))playback.stopAfterMinutes=durationMinutes(String(options.values.get('stop-after')));if(options.values.has('fallback'))playback.fallbackStation=resolveStation(store,String(options.values.get('fallback')));if(options.values.has('clear-fallback'))delete playback.fallbackStation;const reliability={...alarm.reliability};if(options.values.has('grace'))reliability.missedRunGraceMinutes=integer(String(options.values.get('grace')),'grace',0,10080);if(options.values.has('wake'))reliability.wakeIfSupported=true;if(options.values.has('no-wake'))reliability.wakeIfSupported=false;if(options.values.has('guard'))reliability.keepAwakeUntilAlarm=true;if(options.values.has('no-guard'))reliability.keepAwakeUntilAlarm=false;const changesSchedule=options.values.has('once')||options.values.has('time')||options.values.has('days')||options.values.has('timezone');return{...(options.values.has('label')?{label:String(options.values.get('label'))}:{}),...(options.values.has('station')?{station}:{}),...(changesSchedule?{schedule:scheduleEdit(options,alarm.schedule)}:{}),playback,reliability};}
function scheduleFrom(options:Options):AlarmSchedule{if(options.values.has('once')){const input=String(options.values.get('once'));const instant=new Date(input);if(!/(?:Z|[+-]\d{2}:\d{2})$/.test(input)||!Number.isFinite(instant.getTime())||instant.getUTCSeconds()!==0||instant.getUTCMilliseconds()!==0)throw new Error('--once requires an absolute ISO-8601 minute with an offset or Z and zero seconds.');return{type:'once',at:instant.toISOString()};}const time=canonicalizeAlarmTime(required(options,'time'));const days=parseDays(String(options.values.get('days')??'daily'));const timezone=canonicalizeTimeZone(String(options.values.get('timezone')??Intl.DateTimeFormat().resolvedOptions().timeZone));return{type:'recurring',time,weekdays:days,timezone};}
function scheduleEdit(options:Options,current:AlarmSchedule):AlarmSchedule{if(options.values.has('once'))return scheduleFrom(options);if(current.type!=='recurring'&&!options.values.has('time'))throw new Error('Changing days or timezone on a one-time alarm also requires --time.');return{type:'recurring',time:canonicalizeAlarmTime(String(options.values.get('time')??(current.type==='recurring'?current.time:''))),weekdays:options.values.has('days')?parseDays(String(options.values.get('days'))):(current.type==='recurring'?current.weekdays:[1,2,3,4,5,6,7]),timezone:canonicalizeTimeZone(String(options.values.get('timezone')??(current.type==='recurring'?current.timezone:Intl.DateTimeFormat().resolvedOptions().timeZone)))};}
function parseDays(value:string):IsoWeekday[]{if(value==='daily')return[1,2,3,4,5,6,7];if(value==='weekdays')return[1,2,3,4,5];if(value==='weekends')return[6,7];return canonicalizeIsoWeekdays(value.split(',').map(Number));}
function resolveStation(store:JsonLibraryStore,key:string):Station{const state=store.snapshot();const stations=[...state.favorites,...state.imported,...state.recent.map(item=>item.station),...state.alarms.flatMap(alarm=>[alarm.station,...(alarm.playback.fallbackStation?[alarm.playback.fallbackStation]:[])])];const station=stations.find(item=>stationKey(item)===key);if(!station)throw new Error(`Station not found: ${key}. Add it to favorites/imports/recents first.`);return station;}
function parseOptions(args:string[]):Options{const allowed=new Set(['station','once','time','days','timezone','label','volume','fade','stop-after','fallback','grace','disabled','wake','no-wake','guard','no-guard','clear-fallback']);const values=new Map<string,string|true>();const positionals:string[]=[];for(let index=0;index<args.length;index+=1){const arg=args[index]!;if(!arg.startsWith('--')){positionals.push(arg);continue;}const key=arg.slice(2);if(!allowed.has(key))throw new Error(`Unknown alarm option: --${key}`);if(values.has(key))throw new Error(`Duplicate alarm option: --${key}`);if(['disabled','wake','no-wake','guard','no-guard','clear-fallback'].includes(key)){values.set(key,true);continue;}const value=args[++index];if(!value||value.startsWith('--'))throw new Error(`Missing value for --${key}.`);values.set(key,value);}if(values.has('once')&&values.has('time'))throw new Error('Choose either --once or --time, not both.');if(values.has('wake')&&values.has('no-wake'))throw new Error('Choose either --wake or --no-wake.');if(values.has('guard')&&values.has('no-guard'))throw new Error('Choose either --guard or --no-guard.');if(values.has('fallback')&&values.has('clear-fallback'))throw new Error('Choose either --fallback or --clear-fallback.');return{values,positionals};}
function required(options:Options,key:string){const value=options.values.get(key);if(typeof value!=='string'||!value)return (()=>{throw new Error(`Missing --${key}.`);})();return value;}
function requiredPos(values:string[],index:number){const value=values[index];if(!value)throw new Error(alarmUsage());return value;}
function integer(value:string,label:string,min:number,max:number){const number=Number(value);if(!Number.isInteger(number)||number<min||number>max)throw new Error(`${label} must be an integer from ${min} to ${max}.`);return number;}
function durationSeconds(value:string){const match=/^(\d+)(s|m)?$/.exec(value);if(!match)throw new Error('Fade must be seconds (30s) or minutes (1m).');return integer(match[1]!, 'fade',0,3600)*(match[2]==='m'?60:1);}
function durationMinutes(value:string){const match=/^(\d+)(m|h)?$/.exec(value);if(!match)throw new Error('Stop-after must be minutes (60m) or hours (2h).');const minutes=Number(match[1])*(match[2]==='h'?60:1);return integer(String(minutes),'stop-after',1,10080);}
function requireAlarm(store:JsonLibraryStore,id?:string){if(!id)throw new Error(alarmUsage());const alarm=store.getAlarm(id);if(!alarm)throw new Error(`Alarm not found: ${id}`);return alarm;}
async function requireActive(args:string[]=[]){const selectors=parseActiveSelectors(args);const clients=await connectActiveAlarms();const matches=[];for(const client of clients){const status=await client.status();if((!selectors.alarmId||status.alarmId===selectors.alarmId)&&(!selectors.occurrenceAt||status.scheduledAt===selectors.occurrenceAt))matches.push(client);}if(!matches.length)throw new Error('No matching alarm is currently playing.');if(matches.length>1)throw new Error('Multiple alarms are playing; select one with --alarm <id> and optionally --occurrence <ISO>.');return matches[0]!;}
async function syncSaved(scheduler:SchedulerService,alarm:Alarm){try{await scheduler.sync(alarm);}catch(error){throw new Error(`Alarm ${alarm.id} was saved, but scheduler setup is degraded: ${error instanceof Error?error.message:String(error)}`);}}
async function reconcileAlarmGuard(alarm:Alarm,guards=new AlarmGuardService(new AlarmPowerGuardStore())){if(alarm.enabled&&alarm.reliability.keepAwakeUntilAlarm)return guards.start(alarm);await guards.stop(alarm.id);return null;}
function formatAlarm(alarm:Alarm){const next=nextOccurrenceForAlarm(alarm,new Date())?.toISOString()??'none';return`${alarm.enabled?'on ':'off'}\t${alarm.id}\t${alarm.label}\t${alarm.station.name}\t${next}`;}
export function alarmUsage(){return'Usage: radiocli alarm list|show <id>|add --station provider:id (--once ISO | --time HH:mm [--days daily|weekdays|weekends|1,2])|edit <id>|enable <id>|disable <id>|remove <id>|test <id>|sync|doctor|status [--alarm <id> --occurrence <ISO>]|dismiss [--alarm <id> --occurrence <ISO>]|snooze <minutes> [--alarm <id> --occurrence <ISO>]|keep-playing [--alarm <id> --occurrence <ISO>]|guard start <id>|stop|status';}
async function statusesOf(clients:Awaited<ReturnType<typeof connectActiveAlarms>>){return Promise.all(clients.map(client=>client.status()));}
export function runnerPowerActive(active:readonly {alarmId:string;scheduledAt:string}[],entries:readonly {alarmId:string;occurrenceAt?:string;component:string;healthy:boolean;active?:boolean}[]){const playing=new Set(active.map(item=>`${item.alarmId}\0${new Date(item.scheduledAt).toISOString()}`));return entries.some(item=>item.occurrenceAt&&playing.has(`${item.alarmId}\0${new Date(item.occurrenceAt).toISOString()}`)&&item.component==='power'&&item.active===true&&item.healthy);}
async function selectedActiveStatuses(args:string[]){const selectors=parseActiveSelectors(args);return (await statusesOf(await connectActiveAlarms())).filter(status=>(!selectors.alarmId||status.alarmId===selectors.alarmId)&&(!selectors.occurrenceAt||status.scheduledAt===selectors.occurrenceAt));}
export function parseActiveSelectors(args:string[]){let alarmId:string|undefined;let occurrenceAt:string|undefined;for(let index=0;index<args.length;index+=1){const key=args[index];const value=args[++index];if((key!=='--alarm'&&key!=='--occurrence')||!value)throw new Error('Use --alarm <id> and optionally --occurrence <absolute ISO instant>.');if(key==='--alarm')alarmId=value;else{if(!/(?:Z|[+-]\d{2}:\d{2})$/.test(value)||!Number.isFinite(Date.parse(value)))throw new Error('--occurrence must be an absolute ISO instant.');occurrenceAt=new Date(value).toISOString();}}return{alarmId,occurrenceAt};}
