import {chmodSync,existsSync,mkdirSync,readFileSync,renameSync,rmSync,statSync,writeFileSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {defaultAlarmRuntimeDirectory} from './runner.js';

export type AlarmRuntimeHealthEntry={alarmId:string;component:'scheduler'|'power'|'runner';occurrenceAt?:string;healthy:boolean;active?:boolean;message:string;updatedAt:string;nextOccurrence?:string};
type HealthFile={version:1;entries:AlarmRuntimeHealthEntry[]};

/** Machine-local operational state; deliberately excluded from profile exports. */
export class AlarmRuntimeHealthStore{
  constructor(readonly filePath=join(defaultAlarmRuntimeDirectory(),'alarm-health.json'),private readonly now:()=>Date=()=>new Date()){}
  record(entry:Omit<AlarmRuntimeHealthEntry,'updatedAt'>):AlarmRuntimeHealthEntry{const current=this.now();const value={...entry,updatedAt:current.toISOString()};validateEntry(value);const release=acquireHealthLock(this.filePath);try{const entries=pruneEntries([value,...this.list().filter(item=>!(item.alarmId===entry.alarmId&&item.component===entry.component&&item.occurrenceAt===entry.occurrenceAt))],current);this.write({version:1,entries});return value;}finally{release();}}
  get(alarmId:string,component?:AlarmRuntimeHealthEntry['component']){return this.list().filter(item=>item.alarmId===alarmId&&(!component||item.component===component));}
  list():AlarmRuntimeHealthEntry[]{if(!existsSync(this.filePath))return[];try{const file=JSON.parse(readFileSync(this.filePath,'utf8')) as HealthFile;if(file.version!==1||!Array.isArray(file.entries))return[];return file.entries.filter(entry=>{try{validateEntry(entry);return true;}catch{return false;}});}catch{return[];}}
  remove(alarmId:string,component?:AlarmRuntimeHealthEntry['component']){const release=acquireHealthLock(this.filePath);try{this.write({version:1,entries:this.list().filter(item=>item.alarmId!==alarmId||(component&&item.component!==component))});}finally{release();}}
  private write(file:HealthFile){mkdirSync(dirname(this.filePath),{recursive:true,mode:0o700});const temp=`${this.filePath}.tmp-${process.pid}`;try{writeFileSync(temp,`${JSON.stringify(file,null,2)}\n`,{mode:0o600});renameSync(temp,this.filePath);if(process.platform!=='win32')chmodSync(this.filePath,0o600);}catch(error){rmSync(temp,{force:true});throw error;}}
}
function validateEntry(entry:AlarmRuntimeHealthEntry){if(!entry||typeof entry.alarmId!=='string'||!entry.alarmId||!['scheduler','power','runner'].includes(entry.component)||typeof entry.healthy!=='boolean'||(entry.active!==undefined&&typeof entry.active!=='boolean')||typeof entry.message!=='string'||!Number.isFinite(Date.parse(entry.updatedAt))||(entry.occurrenceAt!==undefined&&!Number.isFinite(Date.parse(entry.occurrenceAt)))||(entry.nextOccurrence!==undefined&&!Number.isFinite(Date.parse(entry.nextOccurrence))))throw new Error('Invalid alarm runtime health entry.');}
function pruneEntries(entries:AlarmRuntimeHealthEntry[],now:Date){const activeCutoff=now.getTime()-24*60*60_000;const active=entries.filter(item=>item.active===true&&Date.parse(item.updatedAt)>=activeCutoff).slice(0,128);const counts=new Map<string,number>();const inactive=entries.filter(item=>item.active!==true).filter(item=>{const key=`${item.alarmId}\0${item.component}`;const count=counts.get(key)??0;if(count>=8)return false;counts.set(key,count+1);return true;}).slice(0,256);return[...active,...inactive];}
function acquireHealthLock(filePath:string){const path=`${filePath}.lock`;mkdirSync(dirname(filePath),{recursive:true,mode:0o700});const deadline=Date.now()+1000;while(true){try{mkdirSync(path,{mode:0o700});return()=>rmSync(path,{recursive:true,force:true});}catch(error){if((error as NodeJS.ErrnoException).code!=='EEXIST')throw error;try{if(Date.now()-statSync(path).mtimeMs>10_000){rmSync(path,{recursive:true,force:true});continue;}}catch{continue;}if(Date.now()>=deadline)throw new Error('Alarm runtime health state is busy.');Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10);}}}
