import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {JsonLibraryStore} from '../storage/store.js';
import type {Alarm} from '../types.js';
import {verifyAlarmSetup} from './setup-verification.js';

const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'radiocli-verify-test-'));roots.push(root);const store=new JsonLibraryStore(join(root,'library.json'));const station={id:'test',provider:'playlist' as const,name:'Test FM',tags:[],streamUrl:'https://example.test/live'};const alarm=store.addAlarm({label:'Morning',enabled:true,station,schedule:{type:'once',at:'2030-01-01T08:00:00.000Z'},playback:{volume:65,fadeSeconds:0,stopAfterMinutes:1},reliability:{missedRunGraceMinutes:10,wakeIfSupported:false}});return{alarm,settings:store.snapshot().settings};}
function dependencies(){const releasePower=vi.fn();const releaseVolume=vi.fn();const stop=vi.fn();return{releasePower,releaseVolume,stop,deps:{terminalProbe:vi.fn(async()=> 'darwin:apple-terminal'),inhibitor:{status:()=>({supported:true,active:false,message:'Idle sleep protection works.'}),acquire:vi.fn(async()=>({release:releasePower}))},systemVolume:{acquireMinimum:vi.fn(async()=>({message:'Output raised.',release:releaseVolume}))},backends:()=>['mpv'],resolve:vi.fn(async()=>({url:'https://example.test/live'})),player:vi.fn(()=>({refreshDetectedBackends:vi.fn(),play:vi.fn(async()=>{}),stop})),wait:vi.fn(async()=>{}),controlProbe:vi.fn(async()=>{}),now:()=>new Date('2029-12-31T08:00:00.000Z'),id:()=> 'temporary'}};}
function scheduler(overrides:Record<string,unknown>={}){return{doctor:()=>({supported:true,exactWake:false,catchUpAfterWake:true,message:'ready'}),sync:vi.fn(async()=>new Date('2029-12-31T08:10:00.000Z')),statusAll:vi.fn(async(alarms:Alarm[])=>[{alarmId:alarms[0]!.id,nextOccurrence:'2029-12-31T08:10:00.000Z',native:{installed:true,healthy:true,message:'ready'},health:[]}]),remove:vi.fn(async()=>{}),...overrides};}

describe('alarm setup verification',()=>{
  it('rehearses every runtime layer and removes its disposable native job',async()=>{const {alarm,settings}=fixture();const d=dependencies();const s=scheduler();const updates:unknown[]=[];const report=await verifyAlarmSetup(s as never,alarm,settings,value=>updates.push(value),d.deps);expect(report.state).toBe('passed');expect(report.steps.every(step=>step.state==='passed')).toBe(true);expect(s.sync).toHaveBeenCalledWith(expect.objectContaining({id:'setup-verification-temporary',enabled:true}));expect(s.remove).toHaveBeenCalledWith('setup-verification-temporary');expect(d.releasePower).toHaveBeenCalledOnce();expect(d.releaseVolume).toHaveBeenCalledOnce();expect(d.stop).toHaveBeenCalledOnce();expect(updates.length).toBeGreaterThan(7);});
  it('reports optional volume and power limitations without hiding a successful alarm path',async()=>{const {alarm,settings}=fixture();const d=dependencies();d.deps.inhibitor.acquire=vi.fn(async()=>{throw new Error('policy denied');});d.deps.systemVolume.acquireMinimum=vi.fn(async()=>{throw new Error('mixer unavailable');});const report=await verifyAlarmSetup(scheduler() as never,alarm,settings,()=>{},d.deps);expect(report.state).toBe('warning');expect(report.steps.find(step=>step.id==='power')).toMatchObject({state:'warning'});expect(report.steps.find(step=>step.id==='volume')).toMatchObject({state:'warning'});expect(report.steps.find(step=>step.id==='playback')).toMatchObject({state:'passed'});});
  it('marks scheduler cleanup failures as blockers and never claims readiness',async()=>{const {alarm,settings}=fixture();const d=dependencies();const s=scheduler({remove:vi.fn(async()=>{throw new Error('cleanup denied');})});const report=await verifyAlarmSetup(s as never,alarm,settings,()=>{},d.deps);expect(report.state).toBe('failed');expect(report.steps.find(step=>step.id==='cleanup')).toMatchObject({state:'failed'});});
  it('does not claim success when an audible sample cannot be stopped cleanly',async()=>{const {alarm,settings}=fixture();const d=dependencies();d.deps.player=vi.fn(()=>({refreshDetectedBackends:vi.fn(),play:vi.fn(async()=>{}),stop:vi.fn(async()=>new Promise<void>(()=>{}))}));const report=await verifyAlarmSetup(scheduler() as never,alarm,settings,()=>{}, {...d.deps,wait:vi.fn(async()=>{})});expect(report.state).toBe('failed');expect(report.steps.find(step=>step.id==='playback')).toMatchObject({state:'failed'});},5_000);
  it('attempts cleanup even when native registration reports a hard failure',async()=>{const {alarm,settings}=fixture();const d=dependencies();const s=scheduler({sync:vi.fn(async()=>{throw new Error('registration denied');})});const report=await verifyAlarmSetup(s as never,alarm,settings,()=>{},d.deps);expect(report.state).toBe('failed');expect(s.remove).toHaveBeenCalledOnce();expect(report.steps.find(step=>step.id==='scheduler')).toMatchObject({state:'failed'});expect(report.steps.find(step=>step.id==='cleanup')).toMatchObject({state:'passed'});});
  it('requires a configured alarm for the audible station rehearsal while still cleaning up',async()=>{const {settings}=fixture();const d=dependencies();const s=scheduler();const report=await verifyAlarmSetup(s as never,undefined,settings,()=>{},d.deps);expect(report.state).toBe('failed');expect(report.steps.find(step=>step.id==='playback')?.detail).toMatch(/create at least one alarm/i);expect(s.remove).toHaveBeenCalledOnce();});
});
